version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: vwa_db
      POSTGRES_USER: vwa_user
      POSTGRES_PASSWORD: vwa_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vwa_user -d vwa_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis (for caching and session storage)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://vwa_user:vwa_password@postgres:5432/vwa_db
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-secret-key-change-in-production
      - PORT=8000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start

  # Solana Validator (for local development)
  solana-validator:
    image: solanalabs/solana:v1.16.0
    ports:
      - "8899:8899"  # RPC
      - "8900:8900"  # WebSocket
    command: >
      sh -c "
        solana-test-validator
        --reset
        --quiet
        --rpc-port 8899
        --rpc-bind-address 0.0.0.0
        --faucet-sol 1000000000
        --limit-ledger-size 50000000
      "
    volumes:
      - solana_data:/root/.config/solana

volumes:
  postgres_data:
  redis_data:
  solana_data:
